server.port: 80

server:
  tomcat:
    max-threads: 300

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://192.168.16.211:3309/atlas_register?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: atlas_registe_w
    password: Zf0atdy9zJVd1K9yY7ZxQM7#
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    separator: //
    druid:
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      initial-size: 20
      max-active: 200
      max-wait: 30000
      min-idle: 20
      validationQuery: select 1

logging:
  config: classpath:logback-spring.xml

xxl:
  job:
    admin:
      addresses: http://scheduler.mtech.svc.mfw/
    executor:
      ip:
      appname: atlas-provider
      port: 9993
      logpath: /mfw_data/server_log/xxl-job/jobhandler
      logretentiondays: -1
    accessToken:

# 日志配置
log:
  root:
    level: INFO
  dir: /mfw_rundata/logdata/machine/runtime/json_atlas_provider/

grpc.server.port : 50051

mfw:
  env:
    instanceEnvMap: [staging,product]

mfw.alert.host : http://malert.mtech.svc.mfw

swagger:
  enable: false