server.port: 80

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://db-mgr_callcenter_dev.public.mfw:3328/atlas_register?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: atlas_register_w
    password: RRxxHsuHpDBRBnDaB9CJMS8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    separator: //
    druid:
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      initial-size: 10
      max-active: 100
      max-wait: 30000
      min-idle: 10
      validationQuery: select 1

logging:
  config: classpath:logback-spring.xml

xxl:
  job:
    admin:
      addresses: http://scheduler.mtech.svc.ab/
    executor:
      ip:
      appname: atlas-provider
      port: 9993
      logpath: /mfw_data/server_log/xxl-job/jobhandler
      logretentiondays: -1
    accessToken:

# 日志配置
log:
  root:
    level: INFO
  dir: /mfw_rundata/logdata/machine/runtime/json_atlas_provider/

grpc.server.port : 50051
mfw.alert.host : http://malert.mtech.svc.mfw
