server.port: 8080


spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://db-mgr_callcenter_dev.public.mfw:3328/atlas_register?zeroDateTimeBehavior=convertToNull&useUnicode=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: atlas_register_w
    password: RRxxHsuHpDBRBnDaB9CJMS8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    separator: //
    druid:
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      initial-size: 5
      max-active: 50
      max-wait: 30000
      min-idle: 5
      validationQuery: select 1

logging:
  config: classpath:logback-spring.xml

xxl:
  job:
    admin:
      addresses: http://scheduler.mtech.svc.ab/
    executor:
      ip:
      appname: atlas-provider
      port: 9993
      logpath: /mfw_data/server_log/xxl-job/jobhandler
      logretentiondays: -1
    accessToken:

alert:
  weixin:
    robot: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=d3a98c7d-72d4-47b3-b5bd-0cf59f2a4062

cas:
  sso:
    getauthinfo: https://cas.mafengwo.cn/sso/getauthinfo?app_id=934a&cas_ticket={ticket}
    admin.users: 59186532,68820274,64167340,81678919,76252806,77166585

# 日志配置
log:
  root:
    level: info
  dir: mfw_rundata/logdata/machine/runtime/json_atlas_provider/

grpc.server.port : 50051
