spring:
  application:
    name: atlasadmin-msp
  profiles:
    active: dev


mybatis-plus:
  typeAliasesPackage: com.mfw.atlas.admin.model.po
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: mysql


thymeleaf:
  cache: false
  prefix: classpath:/templates/
  check-template-location: true
  suffix: .html
  encoding: utf-8
  servlet:
    content-type: text/html
  mode: HTML
